import { useState } from 'react';
import { Home, Search, Compass, Clapperboard, Send, Heart, SquarePlus, CircleUserRound, Menu, MoreHorizontal, MessageCircle, Bookmark, Grid3X3, X } from 'lucide-react';
import { CreateDialog } from '../components/shared/CreateDialog';
import { DemoEnvironmentBadge, PlatformSwitcher } from '../components/shared/DemoControls';
import { getPosts } from '../services/social-posts';
import type { SocialPost } from '../types/social';

const nav = [{label:'Home',icon:Home},{label:'Search',icon:Search},{label:'Explore',icon:Compass},{label:'Reels',icon:Clapperboard},{label:'Messages',icon:Send},{label:'Notifications',icon:Heart},{label:'Create',icon:SquarePlus},{label:'Profile',icon:CircleUserRound},{label:'More',icon:Menu}];
const stories = [{name:'Our story',image:'/vamo/mark.svg'},{name:'Copenhagen',image:'/vamo/copenhagen.jpg'},{name:'Vienna',image:'/vamo/vienna.jpg'},{name:'Prague',image:'/vamo/prague.jpg'}];

function InstagramPost({ post }: { post: SocialPost }) {
  const [liked,setLiked] = useState(false);
  const [saved,setSaved] = useState(false);
  return <article className="ig-post"><header><img className="avatar" src="/vamo/mark.svg" alt=""/><div><strong>vamo.travel</strong><span>· {new Date(post.createdAt).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</span></div><button aria-label="Post options" disabled title="Outside the local demo"><MoreHorizontal size={22}/></button></header>{post.imageUrl ? <img className="ig-post-image" src={post.imageUrl} alt={post.text.split('\n')[0]}/> : <div className="ig-text-image">{post.text}</div>}<div className="ig-actions"><button aria-label={liked?'Unlike':'Like'} aria-pressed={liked} onClick={() => setLiked(!liked)}><Heart size={25} fill={liked?'currentColor':'none'}/></button><MessageCircle size={25} aria-hidden="true"/><Send size={24} aria-hidden="true"/><button className="save" aria-label={saved?'Unsave':'Save'} aria-pressed={saved} onClick={() => setSaved(!saved)}><Bookmark size={24} fill={saved?'currentColor':'none'}/></button></div><p className="ig-caption"><strong>vamo.travel</strong> {post.text}</p><small className="ig-time">EDITORIAL DEMO · SAVED LOCALLY</small></article>;
}

export function InstagramDemo() {
  const [open,setOpen] = useState(false);
  const [posts,setPosts] = useState(() => getPosts('instagram'));
  const [selected,setSelected] = useState<SocialPost | null>(null);
  const [toast,setToast] = useState(false);
  function published(post: SocialPost) { setPosts(current => [post,...current]); setToast(true); window.setTimeout(() => setToast(false),3500); }
  return <div className="instagram vamo-ig"><aside className="ig-nav"><div className="ig-wordmark">Instagram <span>Demo</span></div><nav>{nav.map(({label,icon:Icon}) => <button key={label} disabled={!['Create','Profile'].includes(label)} className={label === 'Profile' ? 'active' : ''} onClick={() => label === 'Create' && setOpen(true)} title={label}><Icon size={25} strokeWidth={label === 'Profile' ? 2.6 : 2}/><span>{label}</span></button>)}</nav></aside><main className="ig-main"><section className="ig-feed"><div className="ig-profile-head"><img src="/vamo/mark.svg" alt="Vamo mark"/><div><div className="ig-profile-title"><h1>vamo.travel</h1><button onClick={() => setOpen(true)}>Create post</button></div><p><strong>{posts.length} posts</strong></p><strong>Vamo · Go somewhere good.</strong><p>Fictional travel collective. Places, people and stories worth sharing.<br/>Editorial demo · no live account or bookings.</p></div></div><div className="ig-stories">{stories.map(story => <div className="story" key={story.name}><div className="story-ring"><img src={story.image} alt=""/></div><span>{story.name}</span></div>)}</div><div className="ig-profile-tab"><Grid3X3 size={14}/> POSTS</div><div className="ig-profile-grid">{posts.map(p => <button key={p.id} className="ig-grid-tile" onClick={() => setSelected(p)} aria-label={`Open post: ${p.text.split('\n')[0]}`}><img src={p.imageUrl} alt=""/></button>)}</div></section><aside className="ig-right"><div className="ig-current"><img src="/vamo/mark.svg" alt=""/><div><strong>vamo.travel</strong><span>Vamo</span></div></div><div className="suggestions-head"><strong>About this demo</strong></div><p className="ig-demo-note">These Vamo posts are fictional editorial content. New posts stay in this browser.</p><small>Image credits: Vamo site asset manifest<br/>© 2026 DEMO SOCIAL SIMULATOR</small></aside></main><div className="ig-mobile-nav"><button aria-label="Home" disabled><Home/></button><button aria-label="Search" disabled><Search/></button><button aria-label="Create" onClick={() => setOpen(true)}><SquarePlus/></button><button aria-label="Reels" disabled><Clapperboard/></button><button aria-label="Profile"><CircleUserRound/></button></div><DemoEnvironmentBadge/><PlatformSwitcher/><CreateDialog platform="instagram" open={open} onOpenChange={setOpen} onPublished={published}/>{selected && <div className="ig-detail-backdrop" onClick={() => setSelected(null)}><div className="ig-detail" role="dialog" aria-modal="true" aria-label="Vamo post" onClick={e => e.stopPropagation()}><button className="ig-detail-close" aria-label="Close post" onClick={() => setSelected(null)}><X/></button><InstagramPost post={selected}/></div></div>}{toast && <div className="toast" role="status">Post saved in demo environment</div>}</div>;
}
