import * as Dialog from '@radix-ui/react-dialog';
import { ImagePlus, X } from 'lucide-react';
import { useRef, useState } from 'react';
import { avatar, createPost, imageFileToDataUrl } from '../../services/social-posts';
import type { SocialPlatform, SocialPost } from '../../types/social';
type Props = { platform: SocialPlatform; open: boolean; onOpenChange: (open: boolean) => void; onPublished: (post: SocialPost) => void };
export function CreateDialog({ platform, open, onOpenChange, onPublished }: Props) {
  const [text, setText] = useState(''); const [imageUrl, setImageUrl] = useState<string>(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const input = useRef<HTMLInputElement>(null);
  const isIg = platform === 'instagram';
  async function upload(file?: File) { if (!file) return; if (!file.type.startsWith('image/')) { setError('Please choose an image file.'); return; } try { setImageUrl(await imageFileToDataUrl(file)); setError(''); } catch { setError('Could not preview this image.'); } }
  function publish() { if (!text.trim() || (isIg && !imageUrl)) return; setBusy(true); try { const post: SocialPost = { id: crypto.randomUUID(), platform, authorName: isIg ? 'vamo.travel' : 'Vamo', authorHeadline: isIg ? undefined : 'Fictional travel collective', authorAvatar: avatar('Vamo'), text: text.trim(), imageUrl, createdAt: new Date().toISOString() }; createPost(post); onPublished(post); setText(''); setImageUrl(undefined); setError(''); onOpenChange(false); } catch { setError('Unable to save this post. Try a smaller image.'); } finally { setBusy(false); } }
  return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className={isIg ? 'dialog-content ig-dialog' : 'dialog-content li-dialog'} aria-describedby={undefined}>
    <input ref={input} hidden type="file" accept="image/*" onChange={e => void upload(e.target.files?.[0])}/>
    {isIg ? <><div className="ig-dialog-head"><Dialog.Close aria-label="Close"><X size={20}/></Dialog.Close><Dialog.Title>Create new post</Dialog.Title><button className="dialog-share" disabled={busy || !text.trim() || !imageUrl} onClick={publish}>Save to demo</button></div>{!imageUrl && !text ? <div className="ig-upload" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); void upload(e.dataTransfer.files[0]); }}><ImagePlus size={66} strokeWidth={1.2}/><p>Add a photo for the editorial post</p><button className="blue-button" onClick={() => input.current?.click()}>Select from computer</button></div> : <div className="ig-compose"><div className="ig-preview">{imageUrl ? <img src={imageUrl} alt="Selected post preview"/> : <div className="empty-preview"><ImagePlus size={52}/><button onClick={() => input.current?.click()}>Add an image</button></div>}</div><div className="ig-fields"><div className="compose-user"><img src={avatar('Vamo')} alt=""/><strong>vamo.travel</strong></div><textarea aria-label="Caption" placeholder="Write a Vamo caption..." maxLength={2200} value={text} onChange={e => setText(e.target.value)}/><div className="char-count">{text.length}/2,200</div><div className="field-row"><span>Fictional demo · saved locally</span></div></div></div>}</> : <><div className="li-compose-head"><div className="compose-user"><img src={avatar('Vamo')} alt=""/><div><Dialog.Title>Vamo</Dialog.Title><small>Fictional company page · local demo</small></div></div><Dialog.Close aria-label="Close"><X size={22}/></Dialog.Close></div><textarea className="li-textarea" placeholder="What would Vamo like to share?" aria-label="Post text" value={text} onChange={e => setText(e.target.value)}/>{imageUrl && <div className="li-image-preview"><img src={imageUrl} alt="Selected post preview"/><button onClick={() => setImageUrl(undefined)} aria-label="Remove image"><X size={18}/></button></div>}<div className="li-compose-footer"><div className="li-tools"><button onClick={() => input.current?.click()} title="Add media"><ImagePlus size={20}/><span>Media</span></button></div><button className="li-post-button" disabled={busy || !text.trim()} onClick={publish}>Save to demo</button></div></>}
    {error && <p className="form-error" role="alert">{error}</p>}
  </Dialog.Content></Dialog.Portal></Dialog.Root>;
}
