import * as Dialog from '@radix-ui/react-dialog';
import { ArrowLeft, Check, ChevronRight, ImagePlus, Monitor, Pencil, Smartphone, X } from 'lucide-react';
import { useRef, useState } from 'react';
import { imageFileToDataUrl } from '../../services/social-posts';
import { saveBrevoCampaign } from '../../services/brevo-campaigns';
import { notifyBrevoCampaignStatusChanged } from '../../services/brevo-events';
import { copenhagenSchedule } from '../../services/brevo-schedule';
import type { BrevoCampaign } from '../../types/brevo';
type Section = 'sender' | 'recipients' | 'subject' | 'design' | 'settings';
type Props = { campaign: BrevoCampaign; onChange: (campaign: BrevoCampaign) => void; onBack: () => void; onToast: (message: string) => void };
export function BrevoCampaignSetup({ campaign, onChange, onBack, onToast }: Props) {
  const [editing,setEditing] = useState<Section | null>(null); const [draft,setDraft] = useState(campaign); const [previewOpen,setPreviewOpen] = useState(false); const [scheduleOpen,setScheduleOpen] = useState(false); const [scheduleChoice,setScheduleChoice] = useState<'now'|'later'>('later'); const [scheduleDate,setScheduleDate] = useState(''); const [scheduleTime,setScheduleTime] = useState('10:00'); const [mobilePreview,setMobilePreview] = useState(false); const [error,setError] = useState(''); const imageInput = useRef<HTMLInputElement>(null);
  function edit(section: Section) { setDraft(campaign); setError(''); setEditing(editing === section ? null : section); }
  function save() { try { const next = { ...draft, updatedAt:new Date().toISOString() }; saveBrevoCampaign(next); onChange(next); setEditing(null); onToast('Campaign saved in demo environment'); } catch { setError('Unable to save. Try a smaller image.'); } }
  async function upload(file?: File) { if (!file) return; if (!file.type.startsWith('image/')) { setError('Choose an image file.'); return; } try { const imageUrl = await imageFileToDataUrl(file); setDraft(current => ({...current,imageUrl})); setError(''); } catch { setError('Image preview could not be loaded.'); } }
  const complete = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(campaign.senderEmail) && !!campaign.senderName.trim() && !!campaign.recipients && !!campaign.subject.trim() && !!campaign.body.trim();
  function schedule() {
    if (!complete) { setError('Complete recipients, subject and design before scheduling.'); return; }
    const scheduledFor = copenhagenSchedule(scheduleDate,scheduleTime);
    if (scheduleChoice === 'later' && (!scheduledFor || Date.parse(scheduledFor) <= Date.now())) { setError('Choose a valid future date and time in Europe/Copenhagen.'); return; }
    try {
      const next: BrevoCampaign = { ...campaign, status: scheduleChoice === 'now' ? 'Sent' : 'Scheduled', scheduledFor: scheduleChoice === 'later' ? scheduledFor! : undefined, updatedAt:new Date().toISOString() };
      saveBrevoCampaign(next);
      notifyBrevoCampaignStatusChanged(next);
      onChange(next); setScheduleOpen(false); setError('');
      onToast(scheduleChoice === 'now' ? 'Campaign sent in demo environment only' : 'Campaign scheduled in demo environment');
    } catch { setError('Unable to save this campaign.'); }
  }
  return <main className="br-setup"><div className="br-breadcrumb">Email campaigns <span>/</span> Create an email campaign</div><div className="br-setup-title"><button aria-label="Back to campaigns" onClick={onBack}><ArrowLeft size={20}/></button><h1>{campaign.name}</h1><button aria-label="Edit campaign name" onClick={() => edit('settings')}><Pencil size={17}/></button><span className="br-status-pill">{campaign.status}</span><div className="br-setup-actions"><button className="br-outline-button" onClick={() => setPreviewOpen(true)}>Preview &amp; Test</button><button className="br-dark-button" disabled={!complete || campaign.status !== 'Draft'} onClick={() => { setError(''); setScheduleOpen(true); }}>{campaign.status === 'Draft' ? 'Schedule' : campaign.status}</button></div></div>
    {campaign.scheduledFor && <p className="br-scheduled-for">Scheduled for {new Date(campaign.scheduledFor).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Copenhagen'})} Europe/Copenhagen · Demo only</p>}
    <div className="br-setup-card">
      <div className="br-setup-row"><span className={`br-step-state ${campaign.senderEmail ? 'done' : ''}`}>{campaign.senderEmail ? <Check size={17}/> : '•'}</span><div><h2>Sender</h2><p><strong>{campaign.senderName}</strong> · {campaign.senderEmail}</p></div><button className="br-outline-button" onClick={() => edit('sender')}>Manage sender</button></div>{editing === 'sender' && <div className="br-edit-panel"><div className="br-input-grid"><label>Sender name<input value={draft.senderName} onChange={e => setDraft({...draft,senderName:e.target.value})}/></label><label>Email address<select value={draft.senderEmail} onChange={e => setDraft({...draft,senderEmail:e.target.value})}><option>hello@vamo.example</option><option>newsletter@vamo.example</option></select></label></div><div className="br-panel-actions"><button onClick={() => setEditing(null)}>Cancel</button><button className="br-dark-button" onClick={save} disabled={!draft.senderName.trim() || !draft.senderEmail.trim()}>Save</button></div></div>}
      <div className="br-setup-row"><span className={`br-step-state ${campaign.recipients ? 'done' : ''}`}>{campaign.recipients ? <Check size={17}/> : '•'}</span><div><h2>Recipients</h2><p>{campaign.recipients || 'The people who receive your campaign'}</p></div><button className="br-outline-button" onClick={() => edit('recipients')}>{campaign.recipients ? 'Manage recipients' : 'Add recipients'}</button></div>{editing === 'recipients' && <div className="br-edit-panel"><h3>Send to</h3><p className="br-hint">Choose a fictional demo list. No contacts are imported or emailed.</p><label>Send to<select aria-label="Audience" value={draft.recipients} onChange={e => setDraft({...draft,recipients:e.target.value})}><option value="">Select lists or segments</option><option>Travel subscribers — Denmark</option><option>All travel subscribers</option><option>New subscribers</option></select></label><div className="br-panel-actions"><button onClick={() => setEditing(null)}>Cancel</button><button className="br-dark-button" disabled={!draft.recipients} onClick={save}>Save</button></div></div>}
      <div className="br-setup-row"><span className={`br-step-state ${campaign.subject ? 'done' : ''}`}>{campaign.subject ? <Check size={17}/> : '•'}</span><div><h2>Subject</h2><p>{campaign.subject || 'Add a subject line for this campaign.'}</p></div><button className="br-outline-button" onClick={() => edit('subject')}>{campaign.subject ? 'Edit subject' : 'Add subject'}</button></div>{editing === 'subject' && <div className="br-edit-panel"><div className="br-input-grid"><label>Subject line<input maxLength={150} placeholder="Your subject line" value={draft.subject} onChange={e => setDraft({...draft,subject:e.target.value})}/></label><label>Preview text <span>(optional)</span><input maxLength={200} placeholder="A short preview in the inbox" value={draft.previewText} onChange={e => setDraft({...draft,previewText:e.target.value})}/></label></div><div className="br-inbox-preview"><small>Vamo</small><strong>{draft.subject || 'Your subject line'}</strong><span>{draft.previewText || 'Your preview text will appear here'}</span></div><div className="br-panel-actions"><button onClick={() => setEditing(null)}>Cancel</button><button className="br-dark-button" disabled={!draft.subject.trim()} onClick={save}>Save</button></div></div>}
      <div className="br-setup-row"><span className={`br-step-state ${campaign.body ? 'done' : ''}`}>{campaign.body ? <Check size={17}/> : '•'}</span><div><h2>Design</h2><p>{campaign.body ? 'Email content is ready' : 'Create your email content.'}</p></div><button className="br-outline-button" onClick={() => edit('design')}>{campaign.body ? 'Edit design' : 'Start designing'}</button></div>{editing === 'design' && <div className="br-edit-panel br-design-panel"><div><h3>Simple editor</h3><p className="br-hint">Write the email body, including the approved footer. Images are optional in this simplified demo.</p><textarea aria-label="Email content" placeholder="Write your email here..." value={draft.body} onChange={e => setDraft({...draft,body:e.target.value})}/><input hidden ref={imageInput} type="file" accept="image/*" onChange={e => void upload(e.target.files?.[0])}/><button className="br-outline-button" onClick={() => imageInput.current?.click()}><ImagePlus size={17}/> {draft.imageUrl ? 'Change image' : 'Add image'}</button>{draft.imageUrl && <button className="br-remove-image" onClick={() => setDraft({...draft,imageUrl:undefined})}>Remove image</button>}</div><div className="br-design-preview"><div className="br-email-render"><div className="br-email-brand">Vamo</div>{draft.imageUrl && <img src={draft.imageUrl} alt="Email design preview"/>}<h3>{draft.subject || draft.name}</h3><p>{draft.body || 'Your email content will appear here.'}</p></div></div><div className="br-panel-actions"><button onClick={() => setEditing(null)}>Cancel</button><button className="br-dark-button" disabled={!draft.body.trim()} onClick={save}>Save design</button></div></div>}
      <div className="br-setup-row br-settings-row"><div><h2>Additional settings</h2><p>Advanced sending and tracking settings are outside this demo.</p></div><button className="br-outline-button" disabled title="Outside the local demo">Edit settings</button></div>{editing === 'settings' && <div className="br-edit-panel"><label>Campaign name<input value={draft.name} onChange={e => setDraft({...draft,name:e.target.value})}/></label><div className="br-panel-actions"><button onClick={() => setEditing(null)}>Cancel</button><button className="br-dark-button" disabled={!draft.name.trim()} onClick={save}>Save</button></div></div>}
    </div>{error && !scheduleOpen && <p className="br-form-error" role="alert">{error}</p>}<p className="br-no-send"><ChevronRight size={16}/> Demo mode: send and schedule actions change local status only. No email is sent.</p>
    <Dialog.Root open={scheduleOpen} onOpenChange={setScheduleOpen}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="br-schedule-dialog" aria-describedby={undefined}><div className="br-preview-head"><Dialog.Title>Schedule your email campaign</Dialog.Title><Dialog.Close aria-label="Close schedule dialog"><X size={20}/></Dialog.Close></div><div className="br-schedule-body"><p>Choose when to send this campaign in the demo environment.</p><label className="br-schedule-option"><input type="radio" name="schedule-option" checked={scheduleChoice === 'now'} onChange={() => {setScheduleChoice('now');setError('');}}/><span><strong>Send now</strong><small>Mark this campaign as sent in the demo.</small></span></label><label className="br-schedule-option"><input type="radio" name="schedule-option" checked={scheduleChoice === 'later'} onChange={() => {setScheduleChoice('later');setError('');}}/><span><strong>Schedule for later</strong><small>Choose a date and time for your demo campaign.</small></span></label>{scheduleChoice === 'later' && <div className="br-input-grid"><label>Date<input type="date" value={scheduleDate} onChange={event => {setScheduleDate(event.target.value);setError('');}}/></label><label>Time<input type="time" value={scheduleTime} onChange={event => {setScheduleTime(event.target.value);setError('');}}/></label><label>Timezone<select aria-label="Timezone" defaultValue="Europe/Copenhagen"><option>Europe/Copenhagen</option></select></label></div>}{error && <p className="br-form-error" role="alert">{error}</p>}<p className="br-schedule-notice">No message is sent to contacts. This only updates the simulated campaign.</p><div className="br-dialog-actions"><button className="br-outline-button" onClick={() => setScheduleOpen(false)}>Cancel</button><button className="br-dark-button" onClick={schedule}>{scheduleChoice === 'now' ? 'Send now in demo' : 'Schedule in demo'}</button></div></div></Dialog.Content></Dialog.Portal></Dialog.Root>
    <Dialog.Root open={previewOpen} onOpenChange={setPreviewOpen}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="br-preview-dialog" aria-describedby={undefined}><div className="br-preview-head"><Dialog.Title>Preview &amp; Test</Dialog.Title><div><button className={!mobilePreview ? 'active' : ''} onClick={() => setMobilePreview(false)} aria-label="Desktop preview"><Monitor size={19}/></button><button className={mobilePreview ? 'active' : ''} onClick={() => setMobilePreview(true)} aria-label="Mobile preview"><Smartphone size={19}/></button><Dialog.Close aria-label="Close preview"><X size={21}/></Dialog.Close></div></div><div className="br-preview-meta"><strong>{campaign.subject || 'No subject yet'}</strong><span>From: {campaign.senderName} &lt;{campaign.senderEmail}&gt;</span><span>To: {campaign.recipients || 'No recipients selected'}</span></div><div className={mobilePreview ? 'br-preview-stage mobile' : 'br-preview-stage'}><div className="br-email-render"><div className="br-email-brand">Vamo</div>{campaign.imageUrl && <img src={campaign.imageUrl} alt="Campaign visual"/>}<h2>{campaign.subject || campaign.name}</h2><p>{campaign.body || 'Your email content will appear here.'}</p></div></div></Dialog.Content></Dialog.Portal></Dialog.Root>
  </main>;
}
