import { ChevronDown, ChevronLeft, ChevronRight, FolderPlus, MoreVertical, Pencil, Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { BrevoCampaign } from '../../types/brevo';
type Props = { campaigns: BrevoCampaign[]; onCreate: () => void; onSelect: (campaign: BrevoCampaign) => void };
export function BrevoCampaignList({ campaigns, onCreate, onSelect }: Props) {
  const [query,setQuery] = useState(''); const [status,setStatus] = useState('All statuses'); const [channel,setChannel] = useState('Email');
  const filtered = useMemo(() => campaigns.filter(item => (status === 'All statuses' || item.status === status) && item.name.toLowerCase().includes(query.toLowerCase())),[campaigns,query,status]);
  return <main className="br-campaigns"><div className="br-page-heading"><h1>Campaigns</h1><div><button className="br-outline-button" disabled title="Folder management is outside this demo">Create folder</button><button className="br-dark-button" onClick={onCreate}>Create campaign</button></div></div><div className="br-channel-tabs" role="tablist" aria-label="Campaign channel">{['Email','SMS','WhatsApp'].map(item => <button role="tab" aria-selected={channel === item} className={channel === item ? 'active' : ''} onClick={() => setChannel(item)} key={item}>{item}</button>)}</div>{channel === 'Email' ? <><div className="br-list-toolbar"><label className="br-search"><Search size={17}/><input aria-label="Search campaigns" placeholder="Search for a campaign" value={query} onChange={e => setQuery(e.target.value)}/></label><label className="br-filter"><select aria-label="Filter by status" value={status} onChange={e => setStatus(e.target.value)}><option>All statuses</option><option>Draft</option><option>Scheduled</option><option>Sent</option></select><ChevronDown size={16}/></label><span className="br-pagination">{filtered.length ? 1 : 0}–{filtered.length} of {filtered.length} <button aria-label="Previous page" disabled><ChevronLeft size={16}/></button><strong>1</strong><button aria-label="Next page" disabled><ChevronRight size={16}/></button></span></div><div className="br-campaign-list">{filtered.length ? filtered.map(item => <article className="br-campaign-row" key={item.id}><input type="checkbox" aria-label={`Select ${item.name}`}/><button className="br-campaign-main" onClick={() => onSelect(item)}><strong>{item.name}</strong><span><i className={item.status === 'Scheduled' || item.status === 'Sent' ? 'scheduled' : ''}/> {item.status} &nbsp; Last edited {new Date(item.updatedAt).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</span><small>#{item.id.startsWith('brevo-seed-') ? 396 + Number(item.id.split('-').at(-1)) : item.id.slice(0,8)}</small></button><div className="br-campaign-stats"><div>Recipients<strong>—</strong></div><div>Opens<strong>—</strong></div><div>Clicks<strong>—</strong></div><div>Unsubscribed<strong>—</strong></div></div><button className="br-row-icon" aria-label={`Edit ${item.name}`} onClick={() => onSelect(item)}><Pencil size={17}/></button><button className="br-row-icon" disabled title="Outside the local demo" aria-label={`More actions for ${item.name}`}><MoreVertical size={18}/></button></article>) : <div className="br-empty-list">No campaigns match your search.</div>}</div><div className="br-list-footer"><FolderPlus size={16}/> All campaigns <span>{filtered.length} campaigns</span></div></> : <div className="br-channel-empty">This demo focuses on email campaigns. Choose Email to continue.</div>}</main>;
}
