import { CalendarDays, ChevronLeft, ChevronRight, Plus, Send, UserRound } from 'lucide-react';
import type { BrevoCampaign } from '../../types/brevo';
type Props = { campaigns: BrevoCampaign[]; onCampaigns: () => void; onCreate: () => void; onSelect: (campaign: BrevoCampaign) => void };
export function BrevoHome({ campaigns, onCampaigns, onCreate, onSelect }: Props) {
 const formatter = new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Copenhagen',year:'numeric',month:'2-digit',day:'2-digit'});
 const today = formatter.format(new Date());
 const [year,month] = today.split('-').map(Number);
 const first = new Date(Date.UTC(year,month-1,1));
 const count = new Date(Date.UTC(year,month,0)).getUTCDate();
 const offset = (first.getUTCDay()+6)%7;
 const days = Array.from({length:offset+count},(_,index) => index<offset ? '' : String(index-offset+1));
 const planned = campaigns.filter(item => item.status==='Scheduled' && item.scheduledFor && formatter.format(new Date(item.scheduledFor))===today);
 return <main className="br-home"><div className="br-home-title"><h1>Hello Vamo</h1><button disabled title="Outside the local demo">Customize page</button></div><div className="br-planning"><div className="br-calendar"><div><ChevronLeft size={15}/><strong>{first.toLocaleDateString('en-GB',{month:'long',year:'numeric',timeZone:'UTC'})}</strong><ChevronRight size={15}/></div><div className="br-calendar-grid">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun',...days].map((day,index) => <span className={index>=7 && day === String(new Date(today+'T12:00:00Z').getUTCDate()) ? 'today' : ''} key={index}>{day}</span>)}</div></div><div className="br-planned"><div className="br-planned-heading"><h2>Planned for today</h2><button className="br-dark-button" onClick={onCreate}><Plus size={15}/> Create</button></div><p>{planned.length ? `${planned.length} demo campaign(s) planned for today` : 'Nothing planned for today'}</p>{planned.map(item => <button key={item.id} onClick={() => onSelect(item)}>{item.name}</button>)}<div className="br-tip-grid"><div><UserRound size={23}/><strong>Do you have new contacts to organize?</strong><p>Use segmentation to send personalized messages to your contacts.</p><button onClick={onCampaigns}>Explore campaigns →</button></div><div><Send size={23}/><strong>Expand your reach with email</strong><p>Create a campaign to share your latest travel news.</p><button onClick={onCreate}>Create a campaign →</button></div></div></div></div><div className="br-home-bottom"><div className="br-home-card"><div><h2>Your last campaigns</h2><button onClick={onCreate}>Create a campaign</button></div>{campaigns.slice(0,3).map(item => <button className="br-home-campaign" key={item.id} onClick={() => onSelect(item)}><strong>{item.name}</strong><span>{item.status} · Email</span></button>)}<button className="br-home-all" onClick={onCampaigns}>Go to Campaigns →</button></div><div className="br-home-card"><div><h2>Your contacts</h2><button disabled title="Fictional audience lists only">View contacts</button></div><div className="br-home-metric"><UserRound size={21}/><strong>—</strong><span>Total demo contacts</span></div><div className="br-home-metric"><CalendarDays size={21}/><strong>—</strong><span>New contacts over the last 30 days</span></div></div></div></main>; }
