const $ = (selector,root=document) => root.querySelector(selector);
const $$ = (selector,root=document) => [...root.querySelectorAll(selector)];
const menu = $('.menu-toggle');
function closeMenu(){menu.setAttribute('aria-expanded','false');$('#main-navigation').classList.remove('open');}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));$('#main-navigation').classList.toggle('open',open);});
for(const link of $$('#main-navigation a'))link.addEventListener('click',closeMenu);
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&menu.getAttribute('aria-expanded')==='true'){closeMenu();menu.focus();}});
for(const filter of $$('[data-filter]'))filter.addEventListener('click',()=>{
 for(const button of $$('[data-filter]')){const active=button===filter;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));}
 for(const card of $$('[data-city]'))card.hidden=filter.dataset.filter!=='all'&&filter.dataset.filter!==card.dataset.city;
 const count=$$('[data-city]:not([hidden])').length;$('#filter-status').textContent=`${count} city ${count===1?'story':'stories'}`;
});
const cities={
 copenhagen:{name:'Copenhagen',country:'Denmark',title:'A slower kind of cool.',description:'A few days for canal-side walks, design discoveries, and the pleasure of stopping for coffee. Start with a harbour stroll and let the city set the pace.',days:[['Arrive & settle in','Leave the first afternoon open. Take a walk along Nyhavn and find your own corner of the city.'],['Follow your curiosity','Make space for design, neighbourhood walks and a long coffee break. Choose one thing you really want to see.'],['One more slow morning','Keep the last morning light. A walk, breakfast, and a little time to return to a favourite spot.']]},
 vienna:{name:'Vienna',country:'Austria',title:'Stay for another coffee.',description:'An outline for a city break with room for coffeehouse afternoons, architecture and a little culture. Start with an unhurried walk rather than a list.',days:[['Arrive & find your rhythm','Settle in and take a first walk through the city. Leave time for a coffeehouse pause.'],['A day for culture','Choose an art or architecture visit, then leave the afternoon for the streets and places that catch your eye.'],['A final little ritual','Return to a favourite café or take one last walk before heading home.']]},
 prague:{name:'Prague',country:'Czechia',title:'Take the scenic way.',description:'A starting point for old streets, riverside walks and mornings with a little space. Cross Charles Bridge and follow a side street just because it looks interesting.',days:[['Arrive & wander','Get settled, find the river, and take a first walk without rushing to see everything.'],['Streets with a story','Start with Charles Bridge. Choose one area to explore and leave time for a long lunch or quiet pause.'],['Your own last chapter','Spend the morning revisiting a favourite corner or finding a new one before the journey home.']]}
};
const dialog=$('#story-dialog');
function showStory(markup){$('#dialog-content').innerHTML=markup;hydrateIcons(dialog);dialog.showModal();dialog.scrollTop=0;}
$('.dialog-close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',event=>{if(event.target!==dialog)return;const rect=dialog.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)dialog.close();});
for(const button of $$('[data-trip]'))button.addEventListener('click',()=>{
 const id=button.dataset.trip;const city=cities[id];
 showStory(`<img class="dialog-image" src="assets/photos/${id}.jpg" alt="Winter in ${city.name}"><div class="dialog-copy"><div class="eyebrow">WINTER ESCAPES / ${city.country.toUpperCase()}</div><h2 id="dialog-title">${city.name}.<br><em>${city.title}</em></h2><p>${city.description}</p><h3>A few days, loosely planned.</h3><ol>${city.days.map(([title,text])=>`<li><strong>${title}.</strong> ${text}</li>`).join('')}</ol><p class="dialog-notice">A suggested three-day outline, ready to adapt. Transport, accommodation, opening times and availability still need to be checked when you plan.</p><button class="button" id="choose-trip">Start with ${city.name}<span data-icon="arrow-right"></span></button></div>`);
 $('#choose-trip').addEventListener('click',()=>{$('#city').value=id;dialog.close();$('#plan').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});$('#city').focus({preventScroll:true});});
});
const fieldnotes={
 pace:{tag:'ON GETTING AWAY',title:'The art of leaving a little unplanned.',intro:'Some of the best parts of a short trip happen between the things you planned.',sections:[['Choose one anchor for each day.','A museum, a neighbourhood walk, or a coffeehouse afternoon. Give the day a shape, then leave room around it.'],['Plan by neighbourhood.','Spend more time being somewhere and less time crossing the city to keep up with a list.'],['Keep the first evening light.','Arriving is already a journey. Give yourself a little time to settle in before deciding what comes next.'],['Leave one thing for another time.','You don’t have to see it all. A city can be the beginning of a story rather than a finished checklist.']]},
 winter:{tag:'THE WINTER EDIT',title:'Cold days. Warm little rituals.',intro:'A winter city break invites a different rhythm: a walk, a pause, and somewhere good to sit for a while.',sections:[['Copenhagen: follow the harbour.','Try a canal-side walk, then make time for coffee and a little design inspiration. The suggested collection starts in Nyhavn.'],['Vienna: make an afternoon of it.','A coffeehouse pause can be the plan. Pair it with one cultural stop rather than filling the day from end to end.'],['Prague: take a longer route.','Use the river as a starting point, then explore a side street. Give yourself room to notice the smaller details.']]}
};
for(const button of $$('[data-note]'))button.addEventListener('click',()=>{const note=fieldnotes[button.dataset.note];showStory(`<div class="dialog-copy"><div class="eyebrow">FIELDNOTES / ${note.tag}</div><h2 id="dialog-title">${note.title}</h2><p>${note.intro}</p>${note.sections.map(([title,text])=>`<h3>${title}</h3><p>${text}</p>`).join('')}<p class="dialog-notice">Elseweek editorial inspiration for the fictional Winter Escapes collection.</p></div>`);});
let downloadUrl;
$('#trip-form').addEventListener('submit',event=>{
 event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;
 const data=new FormData(form);const city=cities[data.get('city')];const interests=data.getAll('interests');const trip={city:city.name,month:data.get('month'),nights:data.get('nights'),travellers:data.get('travellers'),interests};
 const content=`ELSEWEEK — YOUR TRIP BRIEF\n\nDestination: ${trip.city}\nMonth: ${trip.month}\nLength: ${trip.nights} nights\nTravellers: ${trip.travellers}\nA little more of: ${interests.length?interests.join(', '):'Room to explore'}\n\nA starting point\n${city.description}\n\nA suggested outline — adapt it to your length of stay\n${city.days.map(([title,text],index)=>`${index+1}. ${title}\n${text}`).join('\n\n')}\n\nNEXT PLANNING STEPS\nConfirm travel dates and transport, choose accommodation, check local opening times and availability, and review costs before booking.\n\nThis is a fictional Elseweek travel-studio demonstration. This brief is inspiration, not a reservation or priced offer. No enquiry has been sent.\n`;
 if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));
 const result=$('#brief-result');result.replaceChildren();result.className='brief-result';
 const heading=document.createElement('h3');heading.textContent=`Your ${city.name} chapter starts here.`;
 const summary=document.createElement('p');summary.textContent=`${trip.nights} nights · ${trip.month} · ${trip.travellers} ${trip.travellers==='1'?'traveller':'travellers'}. Your preferences and suggested outline are ready to keep.`;
 const download=document.createElement('a');download.className='text-action';download.href=downloadUrl;download.download=`elseweek-${data.get('city')}-trip-brief.txt`;download.innerHTML='Download your trip brief <span data-icon="arrow-right"></span>';
 result.append(heading,summary,download);hydrateIcons(result);
});
window.addEventListener('pagehide',()=>{if(downloadUrl)URL.revokeObjectURL(downloadUrl);});
$('#photo-credits').addEventListener('click',()=>showStory(`<div class="dialog-copy"><div class="eyebrow">THE PLACES, PHOTOGRAPHED</div><h2 id="dialog-title">Photo credits.</h2><ul class="credits-list"><li>Copenhagen: <a href="https://unsplash.com/photos/colorful-buildings-line-a-canal-with-boats-at-dusk-ItoGDU0geqY" target="_blank" rel="noopener noreferrer">heino eisner / Unsplash</a></li><li>Vienna: <a href="https://www.pexels.com/photo/tram-in-a-city-street-of-vienna-15604317/" target="_blank" rel="noopener noreferrer">Denisa Lesniaková / Pexels</a></li><li>Prague: <a href="https://www.pexels.com/photo/people-walking-on-the-charles-bridge-in-prague-in-winter-czech-republic-19099385/" target="_blank" rel="noopener noreferrer">Helena Jankovičová Kováčová / Pexels</a></li></ul><p>Photographs are bundled locally. Source and license references are documented in the asset manifest.</p></div>`));
