const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('desktop', {
  login: (email, password) => ipcRenderer.invoke('account:login', email, password),
  logout: () => ipcRenderer.invoke('account:logout'),
  enableAccounts: (email, password) => ipcRenderer.invoke('account:enable', email, password),
  createAccount: (id, email, profile) => ipcRenderer.invoke('account:create', id, email, profile),
  uploadOnboarding: () => ipcRenderer.invoke('onboarding:upload'),
  analyzeOnboarding: (consent) => ipcRenderer.invoke('onboarding:analyze', consent),
  applyOnboarding: (review) => ipcRenderer.invoke('onboarding:apply', review),
  learningAction: (action, payload) => ipcRenderer.invoke('learning:action', action, payload),
  snapshot: () => ipcRenderer.invoke('agent:snapshot'),
  openWork: (kind) => ipcRenderer.invoke('agent:open-work', kind),
  share: (kind, enable) => ipcRenderer.invoke('agent:share', kind, enable),
  ask: (question) => ipcRenderer.invoke('agent:ask', question),
  askDemo: (question) => ipcRenderer.invoke('agent:ask-demo', question),
  aiMode: (enabled) => ipcRenderer.invoke('agent:ai-mode', enabled),
  source: (id) => ipcRenderer.invoke('agent:source', id),
  openSource: (id) => ipcRenderer.invoke('agent:open-source', id),
  updateWork: (kind, data) => ipcRenderer.send('work:update', kind, data),
  onSnapshot: (callback) => { ipcRenderer.on('agent:snapshot', (_, value) => callback(value)); },
  onSharing: (callback) => { ipcRenderer.on('work:sharing', (_, value) => callback(value)); },
  createWorkspace: (company, adminName, email, password) => ipcRenderer.invoke('workspace:create', company, adminName, email, password),
  addPerson: (name, role, department) => ipcRenderer.invoke('workspace:add-person', name, role, department),
  switchPerson: (id) => ipcRenderer.invoke('workspace:switch-person', id),
  importSources: (options) => ipcRenderer.invoke('workspace:import', options),
  importFolder: (options) => ipcRenderer.invoke('workspace:import-folder', options),
  updateSource: (id, action, priority) => ipcRenderer.invoke('workspace:update-source', id, action, priority),
  proposeSource: (id) => ipcRenderer.invoke('workspace:propose-source', id),
  openWorkspaceSource: (id) => ipcRenderer.invoke('workspace:open-source', id),
  readWorkspaceFile: (id) => ipcRenderer.invoke('workspace:read-file', id),
  saveApiKey: (service, value) => ipcRenderer.invoke('workspace:save-key', service, value),
  searchPublicWeb: (query) => ipcRenderer.invoke('agent:web-search', query),
  openWeb: (url) => ipcRenderer.invoke('agent:open-web', url),
  externalWindows: () => ipcRenderer.invoke('agent:external-windows'),
  shareExternal: (id, name) => ipcRenderer.invoke('agent:external-share', id, name),
  reviewExternal: () => ipcRenderer.invoke('agent:external-review'),
});
