let learningRenderKey;
async function learnAction(kind,payload={}) {
 const status=el('learning-status');status.textContent='Saving…';
 try {current=await window.desktop.learningAction(kind,payload);render();status.textContent='Saved on this computer.';
  const next=kind==='confirm'?el('learning-panel').querySelector('.learning-card h4')||el('learning-panel').querySelector('.learning-card h3'):['quiz','answer'].includes(kind)?el('learning-panel').querySelector('.learning-question form')?.closest('.learning-question')?.querySelector('h4')||el('learning-panel').querySelector('.learning-question h4'):['project-start','project-confirm'].includes(kind)?el('learning-panel').querySelector('.project-exercise h4')||el('learning-panel').querySelector('.project-exercise h3'):null;
  if(next){next.tabIndex=-1;next.focus();}
 }
 catch(error){status.textContent=error.message;}
}
function learningButton(label,kind,payload){const b=node('button',label,'secondary-button');b.type='button';b.addEventListener('click',()=>learnAction(kind,payload));return b;}
function guideLink(guide){const b=node('button','Open official Canva guide','source-link');b.type='button';b.addEventListener('click',()=>window.desktop.openWeb(guide.url));return b;}
function renderLearning(){
 const data=current.learning||{configured:false};const key=JSON.stringify([data,current.workspace?.sources,current.workspace?.activePersonId]);if(key===learningRenderKey)return;learningRenderKey=key;
 const panel=el('learning-panel');panel.replaceChildren();
 if(!data.configured){panel.append(node('p','Create a company workspace and select a person in Setup to save learning.'));return;}
 panel.append(node('p',`Learning for ${current.workspace.people.find(p=>p.id===current.workspace.activePersonId)?.name}. Week beginning ${data.week} · Europe/Copenhagen.`,'section-note'));
 const active=data.sessions.find(s=>!s.finishedAt&&!s.excluded&&!s.exercise&&!s.project&&!s.note);
 const lesson=node('article',undefined,'learning-card');lesson.append(node('h3','Canva layout essentials'));
 if(!active){
  lesson.append(node('p','Practise selecting, positioning, aligning and grouping elements. Start with an open Canva design. A shared window is optional; use Work for explicit OCR capture.'));
  const label=node('label','Optional company context');label.htmlFor='learning-source';const select=node('select');select.id='learning-source';select.append(new Option('Tool practice only',''));
  const conflicts=new Set((current.workspace.conflicts||[]).flat());for(const source of current.workspace.sources.filter(s=>s.status==='approved'&&!conflicts.has(s.id)))select.append(new Option(`${source.title} · v${source.version}`,source.id));
  const start=node('button','Start Canva lesson','agent-primary');start.type='button';start.addEventListener('click',()=>learnAction('start',{sourceId:select.value||null}));lesson.append(label,select,start);
 }else{
  const step=data.steps[active.confirmed.length];lesson.append(node('p',`Step ${active.confirmed.length+1} of ${data.steps.length} · Confirmed by you, not automatically verified.`,'section-note'),node('h4',step.title),node('p',step.instruction));
  const help=node('details');help.append(node('summary','I need help with this step'),node('p',step.help));lesson.append(help,guideLink(data.guide));
  if(active.source){lesson.append(node('p',`${active.source.title} · v${active.source.version}${active.sourceAvailable?'':' · no longer available for practice'}`));if(active.sourceAvailable){const b=node('button','Read company context','source-link');b.type='button';b.addEventListener('click',()=>showSource(active.source.id));lesson.append(b);}}
  const next=learningButton('I tried this step — continue','confirm',{sessionId:active.id,stepId:step.id});next.classList.add('agent-primary');lesson.append(next);
 }
 panel.append(lesson);
 for(const session of data.sessions.filter(s=>s.exercise&&!s.finishedAt&&!s.excluded)){
  const exercise=node('article',undefined,'learning-card finding-exercise');const finding=session.exercise;const heading=node('h3',`Practise: ${finding.title}`);heading.tabIndex=-1;
  exercise.append(heading,node('p',`From the shared ${finding.kind} work. This is an employee exercise, not an automatic visual assessment.`));
  const comparison=node('div',undefined,'learning-comparison');comparison.append(node('div',`Before · ${finding.before}\n${finding.problem}`),node('div',`Target · ${finding.action}\nCheck the cited source, then make the edit yourself.`));exercise.append(comparison);
  const open=node('button','Open work window','secondary-button');open.type='button';open.addEventListener('click',()=>window.desktop.openWork(finding.kind).catch(error=>{el('learning-status').textContent=error.message;}));exercise.append(open);
  const sourceButton=node('button',`Read ${finding.source.title}${finding.source.version?` · v${finding.source.version}`:''}`,'source-link');sourceButton.type='button';sourceButton.addEventListener('click',()=>showSource(finding.source.id));exercise.append(sourceButton);
  const form=node('form',undefined,'workspace-form');const label=node('label','What did you change, and what did you check?');const response=node('textarea');response.required=true;response.minLength=10;response.maxLength=1000;response.rows=3;label.append(response);
  const confirm=node('label');const check=node('input');check.type='checkbox';check.required=true;confirm.append(check,document.createTextNode(' I made and reviewed this edit myself.'));
  const submit=node('button','Recheck supported field and save practice','agent-primary');submit.type='submit';form.append(label,confirm,submit);form.addEventListener('submit',e=>{e.preventDefault();learnAction('finding-complete',{sessionId:session.id,reflection:response.value});});exercise.append(form);panel.append(exercise);
 }
 const projectStart=node('details',undefined,'learning-card');projectStart.append(node('summary','Start a task-based exercise'),node('p','Choose a concrete result. You perform the work and confirm each step; Averill does not inspect Canva geometry or verify an exported file.'));
 const projectForm=node('form',undefined,'workspace-form');const projectLabel=node('label','Exercise');const projectSelect=node('select');for(const project of data.projects||[])projectSelect.append(new Option(project.title,project.id));projectLabel.append(projectSelect);
 const projectSourceLabel=node('label','Optional approved company source');const projectSource=node('select');projectSource.append(new Option('Use supplied demo guidance only',''));const projectBlocked=new Set((current.workspace.conflicts||[]).flat());for(const source of current.workspace.sources.filter(source=>source.status==='approved'&&!projectBlocked.has(source.id)))projectSource.append(new Option(`${source.title} · v${source.version}`,source.id));projectSourceLabel.append(projectSource);
 const projectButton=node('button','Start exercise','agent-primary');projectButton.type='submit';projectForm.append(projectLabel,projectSelect,projectSourceLabel,projectSource,projectButton);projectForm.addEventListener('submit',e=>{e.preventDefault();learnAction('project-start',{projectId:projectSelect.value,sourceId:projectSource.value||null});});projectStart.append(projectForm);panel.append(projectStart);
 for(const session of data.sessions.filter(s=>s.project&&!s.finishedAt&&!s.excluded)){
  const project=node('article',undefined,'learning-card project-exercise');const index=session.project.notes.length;project.append(node('h3',session.title),node('p',`Step ${index+1} of ${session.project.steps.length} · ${session.project.tool} · employee confirmed`,'section-note'));
  if(session.source){project.append(node('p',`${session.source.title} · v${session.source.version}${session.sourceAvailable?'':' · approval/version changed; verify the current source'}`));if(session.sourceAvailable){const read=node('button','Read linked source','source-link');read.type='button';read.addEventListener('click',()=>showSource(session.source.id));project.append(read);}}
  if(session.project.demoSource){const demo=node('button','Read supplied demo guidance','source-link');demo.type='button';demo.addEventListener('click',()=>showSource(session.project.demoSource));project.append(demo);}else project.append(guideLink(data.guide));
  for(const [i,note] of session.project.notes.entries())project.append(node('p',`Step ${i+1} confirmed by you: ${note}`,'learning-feedback'));
  const heading=node('h4',session.project.steps[index]);project.append(heading);
  const form=node('form',undefined,'workspace-form');const label=node('label','What did you make or check? Include the file name if you exported one.');const note=node('textarea');note.required=true;note.minLength=10;note.maxLength=1000;note.rows=3;label.append(note);const checkLabel=node('label');const check=node('input');check.type='checkbox';check.required=true;checkLabel.append(check,document.createTextNode(' I completed and checked this step myself.'));const submit=node('button',index===session.project.steps.length-1?'Finish this exercise':'Save and continue','agent-primary');submit.type='submit';form.append(label,checkLabel,submit);form.addEventListener('submit',e=>{e.preventDefault();learnAction('project-confirm',{sessionId:session.id,note:note.value});});project.append(form);panel.append(project);
 }
 const helpCard=node('details',undefined,'learning-card');helpCard.append(node('summary','Ask about a Canva lesson step or inspect selected visible text'));
 helpCard.append(node('p','Type a question about selection, Position, alignment or grouping. Averill answers from this offline lesson. A selected Canva window can be captured once on request; OCR does not verify layout.'));
 const helpForm=node('form',undefined,'workspace-form');const helpLabel=node('label','Your question');const helpInput=node('input');helpInput.type='text';helpInput.required=true;helpInput.maxLength=500;helpLabel.append(helpInput);const helpSubmit=node('button','Get step help','secondary-button');helpSubmit.type='submit';const helpResult=node('p',undefined,'learning-feedback');helpForm.append(helpLabel,helpSubmit);helpForm.addEventListener('submit',e=>{e.preventDefault();const words=helpInput.value.toLowerCase();const step=data.steps.find(s=>[s.id,s.title.toLowerCase()].some(term=>words.includes(term)))||data.steps.find(s=>s.id==='select'&&/shift|multiple|choose/.test(words))||data.steps.find(s=>s.id==='group'&&/shortcut|together/.test(words));helpResult.textContent=step?`${step.title}: ${step.instruction} ${step.help}`:'I cannot answer that from this bounded lesson. Ask about selection, Position, alignment or grouping, or open the official guide.';});helpCard.append(helpForm,helpResult,guideLink(data.guide));
 const capture=node('button','Capture one selected Canva frame','secondary-button');capture.type='button';capture.disabled=!current.externalWindow;capture.addEventListener('click',async()=>{helpResult.textContent='Reading one selected frame…';try{const result=await window.desktop.reviewExternal();helpResult.textContent=`Visible OCR text in ${result.window}: ${result.text||'No readable text detected.'} This does not assess geometry.`;}catch(error){helpResult.textContent=error.message;}});helpCard.append(capture);panel.append(helpCard);
 const activity=node('details',undefined,'learning-card');activity.append(node('summary','Record something else you practised'));
 const form=node('form');form.className='workspace-form';const toolLabel=node('label','Work tool');toolLabel.htmlFor='learning-tool';const tool=node('select');tool.id='learning-tool';for(const name of ['LinkedIn','Newsletter','Canva'])tool.append(new Option(name,name));
 const noteLabel=node('label','What did you do or learn?');noteLabel.htmlFor='learning-note';const note=node('textarea');note.id='learning-note';note.required=true;note.minLength=10;note.maxLength=1000;note.rows=3;
 const sourceLabel=node('label','Optional approved company source');sourceLabel.htmlFor='activity-source';const source=node('select');source.id='activity-source';source.append(new Option('No company source',''));const blocked=new Set((current.workspace.conflicts||[]).flat());for(const s of current.workspace.sources.filter(s=>s.status==='approved'&&!blocked.has(s.id)))source.append(new Option(`${s.title} · v${s.version}`,s.id));
 const checkLabel=node('label');const check=node('input');check.type='checkbox';check.required=true;checkLabel.append(check,document.createTextNode(' I confirm this activity reflects my work.'));
 const submit=node('button','Save confirmed activity','secondary-button');submit.type='submit';form.append(toolLabel,tool,noteLabel,note,sourceLabel,source,checkLabel,submit);form.addEventListener('submit',e=>{e.preventDefault();learnAction('record',{tool:tool.value,note:note.value,sourceId:source.value||null,confirmed:check.checked});});activity.append(form);panel.append(activity);
 const week=node('article',undefined,'learning-card');week.append(node('h3','Your week'),node('p','Review your confirmed activities before starting practice. Excluding a session removes it from practice; the local record remains visible.'));
 const sessions=data.sessions.filter(s=>s.confirmed.some(c=>c.week===data.week)||!s.finishedAt);
 if(!sessions.length)week.append(node('p','No learning recorded this week. Start a lesson and confirm a step.'));
 for(const s of sessions){const row=node('div',undefined,'learning-record');row.append(node('strong',s.title),node('p',`${s.note?'Activity confirmed this week':`${s.confirmed.filter(c=>c.week===data.week).length} steps confirmed this week`}${s.finishedAt&&!s.note?' · lesson finished':''}${s.excluded?' · excluded':''}`));if(s.note)row.append(node('p',s.note));if(s.exercise?.after)row.append(node('p',`Before: ${s.exercise.before} After: ${s.exercise.after} Employee confirmation and deterministic rule check are separate.`));if(!s.excluded)row.append(learningButton('Exclude this session','exclude',{sessionId:s.id}));week.append(row);}
 const begin=learningButton(data.quiz?'Resume or refresh weekly practice':'Start weekly practice','quiz');begin.classList.add('agent-primary');begin.disabled=!sessions.some(s=>!s.excluded&&s.confirmed.some(c=>c.week===data.week));week.append(begin);const weekly=node('details',undefined,'learning-week');weekly.open=Boolean(data.quiz);weekly.append(node('summary','Your week and learning history'),week);panel.append(weekly);
 const remove=node('button','Delete my local learning history','secondary-button learning-delete');remove.type='button';remove.addEventListener('click',()=>{if(window.confirm('Delete all of your local lesson, activity and weekly practice records? This cannot be undone in Averill.'))learnAction('delete-history');});week.append(remove);
 const quiz=data.quiz;if(!quiz)return;
 if(quiz.outdated)panel.append(node('p','Your learning record changed. Refresh weekly practice to include the latest confirmed activities.','section-note'));
 const practice=node('article',undefined,'learning-card');practice.append(node('h3',quiz.finishedAt?'Weekly practice complete':'Weekly practice'),node('p','Feedback supports learning. It is not an employee performance or mastery score.'));
 for(const q of quiz.questions){const card=node('div',undefined,'learning-question');card.append(node('h4',q.prompt));
  if(!q.available){card.append(node('p','This activity or source changed. Refresh weekly practice.'));practice.append(card);continue;}
  if(q.guide)card.append(guideLink(q.guide));if(q.source){const b=node('button',`Read ${q.source.title} · v${q.source.version}`,'source-link');b.type='button';b.addEventListener('click',()=>showSource(q.source.id));card.append(b);}
  const answer=quiz.answers[q.id];if(answer){card.append(node('p',['practice','work'].includes(q.type)?answer.text:`Your answer: ${q.options[answer.choice]}`),node('p',answer.feedback,'learning-feedback'));practice.append(card);continue;}
  const form=node('form');form.className='workspace-form';
  if(['practice','work'].includes(q.type)){
   const label=node('label','What did you try, and what would you check?');const text=node('textarea');text.id=`reflection-${q.id}`;label.htmlFor=text.id;text.required=true;text.minLength=10;text.maxLength=1000;text.rows=3;
   const checkLabel=node('label');const check=node('input');check.type='checkbox';check.required=true;checkLabel.append(check,document.createTextNode(' I tried this operation myself.'));form.append(label,text,checkLabel);
   form.addEventListener('submit',e=>{e.preventDefault();learnAction('answer',{quizId:quiz.id,questionId:q.id,value:{text:text.value,confirmed:check.checked}});});
  }else{
   const field=node('fieldset');const legend=node('legend','Choose an answer');field.append(legend);
   for(const [i,option] of q.options.entries()){const label=node('label');const radio=node('input');radio.type='radio';radio.name='answer';radio.value=String(i);radio.required=true;label.append(radio,document.createTextNode(' '+option));field.append(label);}form.append(field);
   form.addEventListener('submit',e=>{e.preventDefault();learnAction('answer',{quizId:quiz.id,questionId:q.id,value:Number(new FormData(form).get('answer'))});});
  }
  const submit=node('button',['practice','work'].includes(q.type)?'Save practice reflection':'Check my answer','secondary-button');submit.type='submit';form.append(submit);card.append(form);practice.append(card);
 }
 if(quiz.finishedAt){const revisit=quiz.questions.find(q=>quiz.answers[q.id]?.correct===false);const topic=data.steps.find(s=>s.id===revisit?.stepId);practice.append(node('p',topic?`Next practice: ${topic.title}. Try it again in a new layout and consult the guide.`:'Next practice: apply one of these operations in a new layout and check the result yourself.','learning-feedback'));}panel.append(practice);
}
